# English path redirects
# Force because the files exist (root paths still resolve to English)
# Keep this list in alphabetical order
[[redirects]]
  from = "/"
  to = "/en/"
  force = true
[[redirects]]
  from = "/bitcoin-cash-website-notice"
  to = "/en/bitcoin-cash-website-notice.html"
  force = true
[[redirects]]
  from = "/chips"
  to = "/en/chips"
  force = true
[[redirects]]
  from = "/developers"
  to = "/en/developers"
  force = true
[[redirects]]
  from = "/exchanges"
  to = "/en/exchanges"
  force = true
[[redirects]]
  from = "/explorers"
  to = "/en/explorers"
  force = true
[[redirects]]
  from = "/media"
  to = "/en/media"
  force = true
[[redirects]]
  from = "/nodes"
  to = "/en/nodes"
  force = true
[[redirects]]
  from = "/wallets"
  to = "/en/wallets"
  force = true

# Tools subfolder
[[redirects]]
  from = "/tools/"
  to = "/en/tools/"
  force = true
[[redirects]]
  from = "/tools/cashaddr"
  to = "/en/tools/cashaddr"
  force = true
[[redirects]]
  from = "/tools/broadcast"
  to = "/en/tools/broadcast"
  force = true
